import React from 'react'
import Head from 'next/head'
import Sozluk from '@/components/Sozluk'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Lügat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center mt-12">
        <h1 className={`font-roboto-slab font-normal text-9xl text-primary`}>
          Lügat
        </h1>
        <Sozluk />
        <Footer />
      </div>
    </>
  )
}
