import React, { useState } from 'react';
import Head from 'next/head'
import styled from 'styled-components';

const Title = styled.h1`
  font-size: 1.5em;
  color: palevioletred;
`;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: papayawhip;
  height: 100vh;
`;


export default function Home() {
  return (
    <>
      <Head>
        <title>Lügat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>
          Lügat
        </Title>
        <Sozluk />
      </Container>
    </>
  )
}

function Sozluk() {
  const [searchTerm, setSearchTerm] = useState('');
  const [searchResults, setSearchResults] = useState([]);

  const handleSearch = async () => {
    const res = await fetch(`/api/lugat?kelime=${searchTerm}`);
    const data = await res.json();
    setSearchResults(data);
    console.log(searchResults)
    console.log(data)
    
  };

  return (
    <div>
      <input type="text" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
      <button onClick={handleSearch}>Search</button>

      <ul style={{
        color: 'red'}
      }>
      {searchResults.map(item => (
        <li key={item.anlam_sira}>
          <p>{item.anlam}</p>
        </li>
      ))}
      </ul>
    </div>
  );
}