import React from "react";
import Head from "next/head";
import styled from "styled-components";
import Sozluk from "../components/Sozluk";

const Title = styled.h1`
  font-size: 4em;
  color: palevioletred;
`;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4em;
  padding-top: 1em;
  background-color: papayawhip;
  height: 100vh;
  overflow-y: scroll;

  &::-webkit-scrollbar {
    width: 8px; /* genişlik */
  }

  &::-webkit-scrollbar-track {
    background-color: #f1f1f1; /* arka plan rengi */
    border-radius: 5px; /* kenar yarıçapı */
  }
  
  &::-webkit-scrollbar-thumb {
    background-color: palevioletred; /* kaydırma çubuğu rengi */
    border-radius: 5px; /* kenar yarıçapı */
    
    &:hover {
      // background-color: palevioletred;  /* kaydırma çubuğu rengi (üzerine geldiğinde) */
    }
  }

`;

export default function Home() {

  return (
    <>
      <Head>
        <title>Lügat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>Lügat</Title>
        <Sozluk />
      </Container>
    </>
  );
}
